apiVersion: v1
kind: Service
metadata:
    name: sonarqube-np
spec:
    selector: 
       app: sonarqube
    ports:
      - name: sonarqube
        port: 9000
        nodePort: 30009
    type: NodePort