apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin
  namespace: pgadmin
  labels:
    app: pgadmin
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"